spring:
  application:
    name : kafka stream
  kafka:
    streams:
      application-id: app1
      bootstrap-servers: localhost:9092
    properties:
      default:
        deserialization:
          exception:
#            handler: com.kafka.stream.exception.DeserializationExceptionHandler
            handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
        production:
          exception:
            handler: com.kafka.stream.exception.ProductionExceptionHandler


